// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqFiN88eHRXd8udZ5IX97uhmtuso1Zvmo',
    appId: '1:1078026243339:web:ba288714d84b1c4b1fe60e',
    messagingSenderId: '1078026243339',
    projectId: 'hamzageneralstore-4ab35',
    authDomain: 'hamzageneralstore-4ab35.firebaseapp.com',
    storageBucket: 'hamzageneralstore-4ab35.firebasestorage.app',
    measurementId: 'G-Y0GHZS2DS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuctG1be5QaOxJMUklZeufGLqF_eRTX34',
    appId: '1:1078026243339:android:8e44d4b53cb1afcf1fe60e',
    messagingSenderId: '1078026243339',
    projectId: 'hamzageneralstore-4ab35',
    storageBucket: 'hamzageneralstore-4ab35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5H6oXIUZWcHRxl332dlOuMquWEY5dfY4',
    appId: '1:1078026243339:ios:869c7260f731f8f91fe60e',
    messagingSenderId: '1078026243339',
    projectId: 'hamzageneralstore-4ab35',
    storageBucket: 'hamzageneralstore-4ab35.firebasestorage.app',
    iosBundleId: 'com.a3solution.hamzageneralstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5H6oXIUZWcHRxl332dlOuMquWEY5dfY4',
    appId: '1:1078026243339:ios:869c7260f731f8f91fe60e',
    messagingSenderId: '1078026243339',
    projectId: 'hamzageneralstore-4ab35',
    storageBucket: 'hamzageneralstore-4ab35.firebasestorage.app',
    iosBundleId: 'com.a3solution.hamzageneralstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqFiN88eHRXd8udZ5IX97uhmtuso1Zvmo',
    appId: '1:1078026243339:web:f7ffd4c9bf3d8dcf1fe60e',
    messagingSenderId: '1078026243339',
    projectId: 'hamzageneralstore-4ab35',
    authDomain: 'hamzageneralstore-4ab35.firebaseapp.com',
    storageBucket: 'hamzageneralstore-4ab35.firebasestorage.app',
    measurementId: 'G-57NSK7JL1D',
  );
}
